[package]
authors = ["Andrei Sousa <sousandrei@gmail.com>"]
edition = "2021"
name = "fikabot"
version = "0.1.0"


[dependencies]
anyhow = "1.0.58"
axum = "0.5.10"
envy = "0.4.2"
futures-util = "0.3.21"
goauth = "0.13.0"
hex = "0.4.3"
hmac = "0.12.1"
hyper = "0.14.19"
rand = "0.8.5"
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
serde_qs = "0.9.2"
sha2 = "0.10.2"
smpl_jwt = "0.7.1"
thiserror = "1.0.31"
time = "0.3.10"
tokio = { version = "1.19.2", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["full"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.11", features = ["std", "fmt", "json"] }
