[package]
authors = ["Andrei Sousa <sousandrei@gmail.com>"]
edition = "2018"
name = "fika"
version = "0.1.0"


[dependencies]
anyhow = "1.0.44"
chrono = "0.4.19"
cron = "0.8.0"
mongodb = { version = "1.2.0", features = ["sync"], default-features = false }
rand = "0.8.3"
reqwest = { version = "0.11.2", features = ["json"] }
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
serde_qs = "0.8.3"
tokio = { version = "1.3.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }
tracing = "0.1.25"
tracing-subscriber = "0.2.16"
warp = "0.3.0"
