[package]
authors = ["Andrei Sousa <sousandrei@gmail.com>"]
edition = "2021"
name = "fikabot"
version = "0.1.0"


[dependencies]
entity = { path = "entity" }

anyhow = "1.0.64"
axum = "0.5.13"
envy = "0.4.2"
futures-util = "0.3.23"
hex = "0.4.3"
hmac = "0.12.1"
hyper = "0.14.19"
rand = "0.8.5"
reqwest = { version = "0.11.11", features = ["json"] }
sea-orm = { version = "0.9.1", features = [
    "macros",
    "sqlx-mysql",
    "runtime-tokio-rustls",
] }
serde = { version = "1.0.144", features = ["derive"] }
serde_qs = "0.9.2"
sha2 = "0.10.2"
tokio = { version = "1.19.2", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["full"] }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["std", "fmt", "json"] }
