[package]
authors = ["Andrei Sousa <sousandrei@gmail.com>"]
edition = "2018"
name = "lunch"
version = "0.1.0"


[dependencies]
chrono = "0.4.19"
cron = "0.8.0"
hyper = { version = "0.14.4", features = ["server", "http1", "runtime"] }
serde = { version = "1.0.124", features = ["derive"] }
serde_qs = "0.8.3"
tokio = { version = "1.3.0", features = ["macros", "rt-multi-thread", "signal"] }
