[package]
authors = ["Andrei Sousa <sousandrei@gmail.com>"]
edition = "2021"
name = "fikabot"
version = "0.1.1"


[dependencies]
entity = { path = "entity" }

anyhow = "1.0.66"
axum = "0.5.17"
envy = "0.4.2"
futures-util = "0.3.25"
hex = "0.4.3"
hmac = "0.12.1"
hyper = "0.14.23"
rand = "0.8.5"
reqwest = { version = "0.11.13", features = ["json"] }
sea-orm = { version = "0.10.6", features = [
    "macros",
    "sqlx-mysql",
    "runtime-tokio-rustls",
] }
serde = { version = "1.0.147", features = ["derive"] }
serde_qs = "0.9.2"
sha2 = "0.10.6"
tokio = { version = "1.23.0", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.5", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["std", "fmt", "json"] }
