[package]
authors = ["Andrei Sousa <sousandrei@gmail.com>"]
edition = "2021"
name = "fikabot"
version = "0.1.0"


[dependencies]
anyhow = "1.0.52"
async-std = { version = "1.10.0", features = ["attributes"] }
chrono = "0.4.19"
cron = "0.9.0"
futures-util = "0.3.19"
hex = "0.4.3"
hmac = "0.12.0"
mongodb = { version = "2.1.0", default-features = false, features = ["sync"] }
rand = "0.8.4"
reqwest = { version = "0.11.8", features = ["json", "blocking"] }
reusable-fmt = "0.2.0"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
serde_qs = "0.8.5"
sha2 = "0.10.0"
thiserror = "1.0.30"
tide = "0.16.0"
tracing = "0.1.29"
tracing-subscriber = "0.3.5"
