[package]
authors = ["Andrei Sousa <sousandrei@gmail.com>"]
edition = "2021"
name = "fikabot"
version = "0.1.0"


[dependencies]
anyhow = "1.0.44"
async-std = { version = "1.10.0", features = ["attributes"] }
chrono = "0.4.19"
cron = "0.8.0"
futures-util = "0.3.17"
mongodb = { version = "2", default-features = false, features = ["sync"] }
rand = "0.8.3"
reqwest = { version = "0.11.2", features = ["json", "blocking"] }
reusable-fmt = "0.2.0"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
serde_qs = "0.8.3"
thiserror = "1.0.30"
tide = "0.16.0"
tracing = "0.1.25"
tracing-subscriber = "0.2.16"
