[package]
authors = ["Andrei Sousa <sousandrei@gmail.com>"]
edition = "2021"
name = "fikabot"
version = "0.1.0"


[dependencies]
anyhow = "1.0.56"
async-std = { version = "1.10.0", features = ["tokio1", "attributes"] }
chrono = "0.4.19"
cron = "0.9.0"
envy = "0.4.2"
futures-util = "0.3.21"
goauth = "0.11.1"
hex = "0.4.3"
hmac = "0.12.1"
rand = "0.8.5"
reqwest = { version = "0.11.8", features = ["json"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_qs = "0.9.1"
sha2 = "0.10.2"
smpl_jwt = "0.6.1"
thiserror = "1.0.30"
tide = "0.16.0"
time = "0.3"
tracing = "0.1.31"
tracing-subscriber = { version = "0.3.9", features = ["std", "fmt", "json"] }
