[package]
authors = ["Andrei Sousa <sousandrei@gmail.com>"]
edition = "2021"
name = "fikabot"
version = "0.1.0"


[dependencies]
anyhow = "1.0.52"
async-std = { version = "1.10.0", features = ["tokio1", "attributes"] }
chrono = "0.4.19"
cron = "0.9.0"
envy = "0.4.2"
futures-util = "0.3.19"
goauth = "0.11.0"
hex = "0.4.3"
hmac = "0.12.0"
rand = "0.8.4"
reqwest = { version = "0.11.8", features = ["json"] }
serde = { version = "1.0.135", features = ["derive"] }
serde_json = "1.0.74"
serde_qs = "0.8.5"
sha2 = "0.10.0"
smpl_jwt = "0.6.1"
thiserror = "1.0.30"
tide = "0.16.0"
time = "0.3"
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.5", features = ["std", "fmt", "json"] }
