name: Main

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        name: installing toolchain
        with:
          profile: default
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.0.0

      - uses: actions-rs/cargo@v1
        name: fmt
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: clippy
        with:
          command: clippy
          args: --release -- -D warnings

      - uses: actions-rs/cargo@v1
        name: build
        with:
          command: build
          args: --release

      - uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        run: task release TAG=${{ steps.create_release.outputs.tag_name }}
